<a href="https://colab.research.google.com/github/saswatisamal/PythonWithGenAI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
# Import numpy as np and see the version
import numpy as np
print(np.__version__)

#Create a 1D array
arr=np.array([1,2,3,4])
print("Values in array arr:")
print(arr)

#Create 1D array of size 4 initialized with 0
a1=np.zeros(4,dtype=np.int64)
print("Values in array a1:")
print(a1)

#Create 1D array of size 4 initialized with 1
b1=np.ones(5,dtype=np.int64)
print("Values in array b1:")
print(b1)

#Create 1D array using start element=1, end=23(as 24 is exclusive) and stepSize=5
c1=np.arange(1,24,5)
print("Values in array c1:")
print(c1)

#Create 1D array of 5 elements equally spaced using start element=1, end=23(as 24 is exclusive)

d1=np.linspace(1,24,num=5)
print("Values in array d1:")
print(d1)

#Create 1D array of 5 elements where value at each position is the memory state value)
e1=np.empty(5,dtype=np.int64)
print("Values in array e1:")
print(e1)

#Create a 3×3 numpy array of all True’s
trueArr=np.full((3,3),True,dtype=bool)
print(trueArr)
reshapedTrueArr=np.full(9,True,dtype=bool).reshape(3,3)
print(reshapedTrueArr)

# Extract items that satisfy a given condition from 1D array:
#Extract all odd numbers from array
arr=np.array([1,2,7,8,10,15,21])
print(arr)
print(arr[arr%2!=0])


#Replace all odd numbers in arr with -1 affecting the original array
arr=np.array([1,2,7,8,10,15,21])
arr[arr%2!=0]=-1
print (arr)

#Replace all odd numbers in arr with -1 without affecting the original array
arr=np.array([1,2,7,8,10,15,21])
deepCopyOfArr=np.copy(arr)
deepCopyOfArr[deepCopyOfArr%2!=0]=-1
print("Deep copy of original array:")
print (deepCopyOfArr)
print("original array:")
print(arr)

#Convert a 1D array to a 2D array with 2 rows and 5 columns
#In reshaping as well a shallow copy is made as both are referring to same location in memory
arr=np.arange(10)
b=np.reshape(arr,(2,5))
b[0][0]=25
print("Original array:")
print(arr)
print("Reshaped array:")
print(b)


#Stack 2 arrays vertically ,along axis=0
a=np.arange(10).reshape(2,5)
b=np.repeat(1,10).reshape(2,5) # repeats 1 ten times
c=np.vstack((a,b))
print(c)

#Stack the arrays a and b horizontally,along axis=1
a=np.arange(10).reshape(2,5)
b=np.repeat(1,10).reshape(2,5) # repeats 1 ten times
c=np.hstack((a,b))
print(c)
print(c.ndim)
print(c.shape) #(2,10)


# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# This can be achieved by using repeat and tile
#repeat repeats each element that no of times, tile repeat arr that no of times
arr=np.array([1,2,3])
a1=np.repeat(arr,3)
print(a1)
a2=np.tile(arr,3)
print(a2)
result=np.concatenate((a1,a2)) # using concatenate function
result1=np.hstack((a1,a2)) # using horizontal stack
print(result)
print(result1)

# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#  b = np.array([7,2,10,2,7,4,9,4,9,8])
# Output: array([2, 4])
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b) # can use intersect function to find common elements between both
print(c)

# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
c=np.setdiff1d(a,b)
print(c)


# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b)) # It returns the indices where a==b across both the arrays



# Question: Get all items between 5 and 10 from a.
# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a>=5) & (a<=10)])










2.0.2
Values in array arr:
[1 2 3 4]
Values in array a1:
[0 0 0 0]
Values in array b1:
[1 1 1 1 1]
Values in array c1:
[ 1  6 11 16 21]
Values in array d1:
[ 1.    6.75 12.5  18.25 24.  ]
Values in array e1:
[4607182418800017408 4619285842798575616 4623226492472524800
 4625830136007098368 4627448617123184640]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 1  2  7  8 10 15 21]
[ 1  7 15 21]
[-1  2 -1  8 10 -1 -1]
Deep copy of original array:
[-1  2 -1  8 10 -1 -1]
original array:
[ 1  2  7  8 10 15 21]
Original array:
[25  1  2  3  4  5  6  7  8  9]
Reshaped array:
[[25  1  2  3  4]
 [ 5  6  7  8  9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
2
(2, 10)
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[2 4]
[1 2 3 4]
(array([1, 3, 5, 7]),)
[ 6  9 10]
(array([1, 2, 6]),)


# New Section

In [7]:
import numpy as np
#Return max elements at position for array a and b
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(np.where(a>b,a,b)) # returns max of element wise in both the array

#Method 2
def maxx(x,y):
    if(x>y):
        return x
    else:
        return y
maximum=[maxx(x,y) for x,y in map(lambda x,y:(x,y),a,b)]
print(np.array(maximum))

[6 7 9 8 9 7 5]
[6 7 9 8 9 7 5]


In [17]:
#How to swap two columns in a 2d numpy array ex: swap 0th and 1st col

a=np.arange(9)
print(a)
b=np.reshape(a,(3,3))
print(b)
#Reorder columns
#c=b[:,[1,0,2]]
#print(c)

#Reorder rows
d=b[[2,1,0],:]
print (d)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [21]:

 #How to reverse the rows of a 2D array
import numpy as np
a=np.arange(9)
print(a)
b=np.reshape(a,(3,3))
#Slicing syntax is [start:stop:step]
#If step is not mentioned it takes=1
c=b[::-1,:]
print(c)




[0 1 2 3 4 5 6 7 8]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [22]:
# How to reverse the columns of a 2D array
a=np.arange(9)
print(a)
b=np.reshape(a,(3,3))
print(b)
#Reverse columns in a 2D array :
c=b[:,::-1]
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
