<a href="https://colab.research.google.com/github/saswatisamal/PythonWithGenAI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Import numpy as np and see the version
import numpy as np
print(np.__version__)

#Create a 1D array
arr=np.array([1,2,3,4])
print("Values in array arr:")
print(arr)

#Create 1D array of size 4 initialized with 0
a1=np.zeros(4,dtype=np.int64)
print("Values in array a1:")
print(a1)

#Create 1D array of size 4 initialized with 1
b1=np.ones(5,dtype=np.int64)
print("Values in array b1:")
print(b1)

#Create 1D array using start element=1, end=23(as 24 is exclusive) and stepSize=5
c1=np.arange(1,24,5)
print("Values in array c1:")
print(c1)

#Create 1D array using start element=1, end=23(as 24 is exclusive) and stepSize=5

d1=np.linspace(1,24,num=5)
print("Values in array d1:")
print(d1)


e1=np.empty(5)
print("e1: "+e1)






2.0.2
Values in array arr:
[1 2 3 4]
Values in array a1:
[0 0 0 0]
Values in array b1:
[1 1 1 1 1]
Values in array c1:
[ 1  6 11 16 21]
Values in array d1:
[ 1.    6.75 12.5  18.25 24.  ]


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U4'), dtype('float64')) -> None

# New Section